<div class="masthead">
  <h3 class="muted">DIN DIGITAL SKELETON</h3>
  
  <?php if(isset($data['nav']) && count($data['nav'])): ?>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <ul class="nav">
          <?php foreach ($data['nav'] as $row): ?>
            <li class="active">
                <a title="<?php echo $row['title']; ?>" href="<?php echo $row['uri']; ?>">
                    <?php echo $row['title']; ?>
                </a>
            </li>
          <?php endforeach; ?>
        </ul>
      </div>
    </div>
  </div><!-- /.navbar -->
  <?php endif; ?>
  
</div>