<section class="container_base">
  <?php if ( isset($data['nav']) && count($data['nav']) ): ?>
    <ul class="menu_header">
      <?php foreach ( $data['nav'] as $row ): ?>
        <li>
          <a title="<?php echo $row['title']; ?>" href="<?php echo $row['link']; ?>" target="<?php echo $row['target']; ?>"><?php echo $row['title']; ?></a>
          <?php if ( isset($row['dropdown']) && count($row['dropdown']) ): ?>
            <ul class="<?php echo $row['class']; ?>">
              <?php foreach ( $row['dropdown'] as $nav_dropdown ): ?>
                <li>
                  <a title="<?php echo $nav_dropdown->getTitle(); ?>" href="<?php echo $nav_dropdown->getLink(); ?>" target="<?php echo $nav_dropdown->getTarget(); ?>"><?php echo $nav_dropdown->getTitle(); ?></a>
                </li>
              <?php endforeach; ?>
            </ul>
          <?php endif; ?>
        </li>
      <?php endforeach; ?>
    </ul>
  <?php endif; ?>
</section>