<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="images/favicon.png">

    <title>DIN DIGITAL</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,400italic,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:300,200,100' rel='stylesheet' type='text/css'>

    <!-- Bootstrap core CSS -->
    <link href="/admin/js/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="/admin/fonts/font-awesome-4/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/admin/js/jquery.select2/select2.css" />
    <link rel="stylesheet" type="text/css" href="/admin/js/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css" />
    <link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.10.3/themes/redmond/jquery-ui.css" />
    <link href="/admin/js/spectrum/spectrum.css" rel="stylesheet" />
    <link href="/admin/css/style.css" rel="stylesheet" />

    <script src="//code.jquery.com/jquery-1.9.1.js"></script>
    <script src="//code.jquery.com/ui/1.10.3/jquery-ui.js" type="text/javascript"></script>
    <script type="text/javascript" src="/admin/js/plupload/js/plupload.full.js"></script>
    <script type="text/javascript" src="/admin/js/plupload/js/jquery.plupload.queue/jquery.plupload.queue.js"></script>
    <script type="text/javascript" src="/admin/js/ajaxform/jquery.form.js"></script>
    <script src="/admin/js/jquery.select2/select2.min.js" type="text/javascript"></script>
    <script src="/admin/js/spectrum/spectrum.js" type="text/javascript"></script>
    <script src="/admin/js/daterangepicker/date.js" type="text/javascript"></script>
    <script src="/admin/js/daterangepicker/daterangepicker.js" type="text/javascript"></script>
    <script src="/admin/js/jquery.maskedinput/jquery.maskedinput.js" type="text/javascript"></script>
    <script type="text/javascript" src="/admin/js/scripts.js"></script>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/admin/js/bootstrap/dist/js/bootstrap.min.js"></script>

  </head>

  <body>

    <!-- Fixed navbar -->
    <div id="head-nav" class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="fa fa-gear"></span>
          </button>
          <a class="navbar-brand" href="#"><span>DIN DIGITAL</span></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/admin/index/index/">Home</a></li>
            <li><a href="#about">About</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contact <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="dropdown-submenu"><a href="#">Sub menu</a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                  </ul>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Large menu <b class="caret"></b></a>
              <ul class="dropdown-menu col-menu-2">
                <li class="col-sm-6 no-padding">
                  <ul>
                    <li class="dropdown-header"><i class="fa fa-group"></i>Users</li>
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="dropdown-header"><i class="fa fa-gear"></i>Config</li>
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                  </ul>
                </li>
                <li  class="col-sm-6 no-padding">
                  <ul>
                    <li class="dropdown-header"><i class="fa fa-legal"></i>Sales</li>
                    <li><a href="#">New sale</a></li>
                    <li><a href="#">Register a product</a></li>
                    <li><a href="#">Register a client</a></li>
                    <li><a href="#">Month sales</a></li>
                    <li><a href="#">Delivered orders</a></li>
                  </ul>
                </li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right user-nav">
            <li class="dropdown profile_menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <?php echo $data['user']['avatar_img'] ?>
                <?php echo $data['user']['nome'] ?> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="/admin/config/cadastro/">Meus Dados</a></li>
                <li class="divider"></li>
                <li><a href="/admin/usuario_auth/logout/">Logout</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right not-nav">
            <li class="button dropdown">
              <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"><i class=" fa fa-comments"></i></a>
              <ul class="dropdown-menu messages">
                <li>
                  <div class="nano nscroller">
                    <div class="content">
                      <ul>
                        <li>
                          <a href="#">
                            <img src="/admin/images/avatar2.jpg" alt="avatar" /><span class="date pull-right">13 Sept.</span> <span class="name">Daniel</span> I'm following you, and I want your money!
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <img src="/admin/images/avatar_50.jpg" alt="avatar" /><span class="date pull-right">20 Oct.</span><span class="name">Adam</span> is now following you
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <img src="/admin/images/avatar4_50.jpg" alt="avatar" /><span class="date pull-right">2 Nov.</span><span class="name">Michael</span> is now following you
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <img src="/admin/images/avatar3_50.jpg" alt="avatar" /><span class="date pull-right">2 Nov.</span><span class="name">Lucy</span> is now following you
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <ul class="foot"><li><a href="#">View all messages </a></li></ul>
                </li>
              </ul>
            </li>
            <li class="button dropdown">
              <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-globe"></i><span class="bubble">2</span></a>
              <ul class="dropdown-menu">
                <li>
                  <div class="nano nscroller">
                    <div class="content">
                      <ul>
                        <li><a href="#"><i class="fa fa-cloud-upload info"></i><b>Daniel</b> is now following you <span class="date">2 minutes ago.</span></a></li>
                        <li><a href="#"><i class="fa fa-male success"></i> <b>Michael</b> is now following you <span class="date">15 minutes ago.</span></a></li>
                        <li><a href="#"><i class="fa fa-bug warning"></i> <b>Mia</b> commented on post <span class="date">30 minutes ago.</span></a></li>
                        <li><a href="#"><i class="fa fa-credit-card danger"></i> <b>Andrew</b> killed someone <span class="date">1 hour ago.</span></a></li>
                      </ul>
                    </div>
                  </div>
                  <ul class="foot"><li><a href="#">View all activity </a></li></ul>
                </li>
              </ul>
            </li>
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div id="cl-wrapper">

      {$NAV}

      <div class="container-fluid" id="pcont">

        <div class="cl-mcont">

          {$CONTENT}

        </div>

      </div>

    </div>

    <div id="loading_overlay">
      <div class="loading_message round_bottom">
        <img src="/adm/images/loading.gif" alt="Carregando" />
      </div>
    </div>

  </body>
</html>
