<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="images/favicon.png">

    <title><?php echo CLIENTNAME; ?> - Painel de Controle</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300' rel='stylesheet' type='text/css'>
    <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"/>
    <link href="/backend/assets/css/app.min.css" rel="stylesheet"/>

    <script src="//code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="/backend/assets/js/app.min.js"></script>

    <script src="/backend/assets/ck/ckeditor365/ckeditor.js"></script>
    <script src="/backend/assets/ck/ckeditor365/adapters/jquery.js"></script>
    <script src="/backend/assets/ck/ckfinder23/ckfinder.js"></script>

  </head>

  <body>

    <!-- Fixed navbar -->
    <div id="head-nav" class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="fa fa-gear"></span>
          </button>
          <a class="navbar-brand" href="#"><span><?php echo CLIENTNAME; ?></span></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right user-nav">
            <li class="dropdown profile_menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <?php echo $data['admin']['avatar_img'] ?>
                <?php echo $data['admin']['name'] ?> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="/admin/config/save/">Meus Dados</a></li>
                <li class="divider"></li>
                <li><a href="/admin/admin_auth_logout/">Logout</a></li>
              </ul>
            </li>
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div id="cl-wrapper">

      {$NAV}

      <div class="container-fluid" id="pcont">

        <div class="cl-mcont">

          {$CONTENT}

        </div>

      </div>

    </div>

    <div id="loading_overlay">
      <div class="loading_message round_bottom">
        <img src="/backend/images/loading.gif" alt="Carregando" />
      </div>
    </div>

  </body>
</html>
