<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/admin/images/favicon.png">

    <title><?php echo CLIENTNAME; ?> - Painel de Controle</title>

    <?php echo $data['assets']['css']['css_admgoogle']; ?>
    <?php echo $data['assets']['css']['css_admlogin']; ?>

  </head>

  <body class="texture">

    {$CONTENT}

    <?php echo $data['assets']['js']['js_admjquery']; ?>
    <?php echo $data['assets']['js']['js_admlogin']; ?>

  </body>
</html>
