<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/admin/images/favicon.png">

    <title><?php echo CLIENTNAME; ?> - Painel de Controle</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300' rel='stylesheet' type='text/css'>
    <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"/>
    <link href="/backend/assets/css/app.min.css" rel="stylesheet"/>

  </head>

  <body class="texture">

    {$CONTENT}

    <script src="//code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="/backend/assets/js/login.min.js"></script>

  </body>
</html>
