<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/admin/images/favicon.png">

    <title>DIN DIGITAL</title>
    <link href='/admin/css/google_open_sans.css' rel='stylesheet' type='text/css'>
    <link href='/admin/css/google_raleway.css' rel='stylesheet' type='text/css'>

    <?php echo $data['assets']['css']['adm_login']; ?>

  </head>

  <body class="texture">

    {$CONTENT}

    <script src="/admin/js/jquery-1.9.1.js"></script>
    <?php echo $data['assets']['js']['adm_login']; ?>

  </body>
</html>
