<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="images/favicon.png">

    <title>DIN DIGITAL - SKELETON</title>

    <?php echo $data['assets']['css']['base']; ?>

  </head>

  <body>
      
      <div class="container">
          
          {$HEADER}
          
          {$CONTENT}
          
          {$FOOTER}
          
      </div>
      
    <?php echo $data['assets']['js']['jquery']; ?>
    <?php echo $data['assets']['js']['base']; ?>
  
  </body>
  
</html>
