<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<?php echo $data['settings']['description'] ?>">
    <meta name="author" content="DIN DIGITAL">
    <link rel="shortcut icon" href="images/favicon.png">

    <title><?php echo $data['settings']['title'] ?></title>

    <?php echo $data['assets']['css']['site']; ?>

  </head>

  <body role="document">
          
      {$HEADER}
          
      <div class="container theme-showcase" role="main">
          
          {$CONTENT}
          
          {$FOOTER}
          
      </div>
      
    <?php echo $data['assets']['js']['jquery']; ?>
    <?php echo $data['assets']['js']['site']; ?>
  
  </body>
  
</html>
