<div class="col-sm-12">
  <div class="content">
    <?php if ( isset($data['saved_msg']) ): ?>
      <div class="alert alert-success alert-success-fade">
        <i class="fa fa-check sign"></i><strong><?php echo $data['saved_msg']; ?></strong>
      </div>
    <?php endif; ?>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="fa fa-check sign"></i><strong>Sucesso!</strong>
      <div></div>
    </div>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="fa fa-times-circle sign"></i>
      <strong>Erro!</strong>&nbsp;&nbsp;Veja abaixo os erros de validação:
      <div></div>
    </div>
  </div>
</div>