<div class="col-sm-12">
  <div class="content">
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="fa fa-check sign"></i><strong>Sucesso!</strong>
      <div></div>
    </div>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="fa fa-times-circle sign"></i>
      <strong>Erro!</strong>&nbsp;&nbsp;Veja abaixo os erros de validação:
      <div></div>
    </div>
  </div>
</div>