<?php if ( !count($data['list']) ): ?>
  <div class="header">
    <h4>Sua precisa não encontrou resultados</h4>
  </div>
<?php else: ?>
  <div class="row">
    <div class="col-sm-12">
      <div class="pull-left">
        <div class="dataTables_info" id="datatable_info">
          Exibindo <?php echo $data['paginator']['subtotal']; ?> de <?php echo $data['paginator']['total']; ?> resultados
        </div>
      </div>
      <div class="pull-right">
        <div class="dataTables_paginate paging_bs_normal">
          <ul class="pagination">
            <?php echo $data['paginator']['numbers']; ?>
          </ul>
        </div>
      </div>
      <div class="clearfix">
      </div>
    </div>
  </div>
<?php endif; ?>