<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="images/favicon.png">

    <title>DIN DIGITAL</title>

    <link href="/admin/js/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
    <link href="/admin/css/style.css" rel="stylesheet" />

  </head>

  <body class="texture">

    <div id="cl-wrapper" class="error-container">
      <div class="page-error">
        <h1 class="number text-center">404</h1>
        <h2 class="description text-center">Desculpe, esta página não existe</h2>
        <h3 class="text-center">Clique aqui e volte a página <a href="/admin/index/index/">inicial</a>.</h3>
      </div>
      <div class="text-center copy">&copy; 2014 <a href="#">DIN DIGITAL</a></div>

    </div>

  </body>
</html>
