<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cache</h3>
      </div>
      <div class="content">

        <form id="main_form" class="ajaxform form-horizontal group-border-dashed" method="post" style="border-radius: 0px;" onsubmit="return false;">

          <div class="form-group form-group-submit">
            <span class="loadingsubmit"></span>
            <button type="submit" class="btn btn-default" tabindex="-1">Limpar Cache</button>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label" for="active">Todo o Cache?</label>
            <div class="col-sm-10">
              <label class="checkbox-inline"><input type="checkbox" name="all" id="all" /></label>
            </div>
          </div>

        <div class="form-group">
            <label class="col-sm-2 control-label" for="active">Cache da Home?</label>
            <div class="col-sm-10">
              <label class="checkbox-inline"><input type="checkbox" name="home" id="home" /></label>
            </div>
          </div>
            
          <div class="form-group">
            <label class="col-sm-2 control-label">Links</label>
            <div class="col-sm-10">
              <input name="uri" class="tags" type="hidden" value="" />
            </div>
          </div>

          <div class="form-group form-group-submit">
            <span class="loadingsubmit"></span>
            <button type="submit" class="btn btn-default" tabindex="-1">Limpar Cache</button>
          </div>

        </form>
      </div>
    </div>

  </div>
</div>