<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Ítens postados no Facebook</h3>
      </div>
      <div class="content">
        <div class="form-horizontal group-border-dashed" style="border-radius: 0px;">
          <div class="form-group form-group-submit">
            <span class="loadingsubmit"></span>
            <div class="input-group">
              <a href="<?php echo $data['redirect']; ?>" title="Voltar para a lista" class="btn btn-default btn-rad btn_space">Voltar</a>
            </div>
          </div>
          <?php foreach ( $data['posts'] as $post ): ?>
            <div class="form-group">
              <strong>Enviado em <?php echo $post['date'] ?></strong>
            </div>

            <div class="form-group">
              <label class="col-sm-2 control-label" for="active">Nome</label>
              <div class="col-sm-10">
                  <label class="checkbox-inline"><?php echo $post['name'] ?></label>
              </div>
            </div>

            <div class="form-group">
              <label class="col-sm-2 control-label" for="active">Link</label>
              <div class="col-sm-10">
                <label class="checkbox-inline"><?php echo $post['link'] ?></label>
              </div>
            </div>

            <?php if ( $post['picture'] != '' ): ?>
              <div class="form-group">
                <label class="col-sm-2 control-label" for="active">Imagem</label>
                <div class="col-sm-10">
                  <label class="checkbox-inline">
                    <?php echo $post['picture'] ?>
                    <br />
                    <img src="<?php echo $post['picture'] ?>" />
                  </label>
                </div>
              </div>
            <?php endif; ?>

            <div class="form-group">
              <label class="col-sm-2 control-label" for="active">Descrição</label>
              <div class="col-sm-10">
                <label class="checkbox-inline"><?php echo $post['description'] ?></label>
              </div>
            </div>

            <div class="form-group">
              <label class="col-sm-2 control-label" for="active">Mensagem</label>
              <div class="col-sm-10">
                <label class="checkbox-inline"><?php echo $post['message'] ?></label>
              </div>
            </div>

          <?php endforeach; ?>
        </div>
      </div>
    </div>

  </div>
</div>