<input type="hidden" id="link_prefix" value="/admin/lixeira/" />

<div class="row">
  <div class="col-md-12">

    {$ALERT}

    <div class="block-flat">
      <div class="header">
        <h3>Lixeira</h3>
      </div>

      <div class="content">
        <form method="get" class="form_busca">
          <div class="col-sm-4 col-md-4 col-lg-2">
            <input class="form-control" name="titulo" type="text" placeholder="Busca por título" value="<?php echo $data['busca']['titulo']; ?>">
          </div>
          <div class="col-sm-4 col-md-4 col-lg-2">
            <?php echo $data['busca']['secao']; ?>
          </div>
          <input type="button" value="Limpar" class="limpar_busca btn btn-default btn-rad" />
          <input type="submit" value="Buscar" class="btn btn-info btn-rad" />
        </form>
      </div>

      <div class="content">
        <div class="col-lg-12 pull-left">
          <a href="#" title="Restaurar Selecionados" class="btn btn-primary btn-rad lixeira_re">Restaurar Selecionados</a>
          <a href="#" title="Excluir Selecionados Permamentemente" class="lixeira_ex btn btn-danger btn-rad">Excluir Selecionados Permamentemente</a>
        </div>
        <br style="clear: both;" />
      </div>

      <div class="content">
        <div class="table-responsive">
          <table class="table no-border hover">
            <thead class="no-border">
              <tr>
                <th style="width:2%;"><input type="checkbox" name="excluir[]" id="excluir_all" /></th>
                <th style="width:25%;"><strong>Data</strong></th>
                <th><strong>Título</strong></th>
                <th style="width:15%;"><strong>Seção</strong></th>
              </tr>
            </thead>
            <tbody class="no-border-y">
              <?php foreach ( $data['list'] as $row ): ?>
                <tr>
                  <td><input class="excluir" type="checkbox" name="excluir[]" id="exc_<?php echo $row['name']; ?>_<?php echo $row['id']; ?>" /></td>
                  <td><?php echo $row['del_data']; ?></td>
                  <td><?php echo $row['titulo']; ?></td>
                  <td><?php echo $row['secao']; ?></td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>

          <?php if ( !count($data['list']) ): ?>
            <div class="header">
              <h4>Sua precisa não encontrou resultados</h4>
            </div>
          <?php else: ?>
            <div class="row">
              <div class="col-sm-12">
                <div class="pull-left">
                  <div class="dataTables_info" id="datatable_info">
                    Exibindo <?php echo $data['paginator']['subtotal']; ?> de <?php echo $data['paginator']['total']; ?> resultados
                  </div>
                </div>
                <div class="pull-right">
                  <div class="dataTables_paginate paging_bs_normal">
                    <ul class="pagination">
                      <?php echo $data['paginator']['numbers']; ?>
                    </ul>
                  </div>
                </div>
                <div class="clearfix">
                </div>
              </div>
            </div>
          <?php endif; ?>

        </div>
      </div>
    </div>
  </div>
</div>

