<input type="hidden" id="link_prefix" value="/admin/log/" />

<div class="row">
  <div class="col-md-12">

    {$ALERT}

    <div class="block-flat">
      <div class="header">
        <h3>Lista de Log</h3>
      </div>

      <div class="content">
        <form method="get" class="form_search">
          <div class="col-sm-4 col-md-4 col-lg-2">
            <input class="form-control" name="admin" type="text" placeholder="Busca por nome de administrador" value="<?php echo $data['search']['admin']; ?>">
          </div>
          <div class="col-sm-4 col-md-4 col-lg-2">
            <input class="form-control" name="description" type="text" placeholder="Busca por descrição" value="<?php echo $data['search']['description']; ?>">
          </div>
          <div class="col-sm-4 col-md-4 col-lg-2">
            <?php echo $data['search']['action']; ?>
          </div>
          <div class="col-sm-4 col-md-4 col-lg-2">
            <?php echo $data['search']['tbl']; ?>
          </div>
          <input type="button" value="Limpar" class="clean_search btn btn-default btn-rad" />
          <input type="submit" value="Buscar" class="btn btn-info btn-rad" />
        </form>
      </div>

      <div class="content">
        <div class="table-responsive">
          <table class="table no-border hover">
            <thead class="no-border">
              <tr>
                <th style="width:15%;"><strong>Data</strong></th>
                <th style="width:15%;"><strong>Usuário</strong></th>
                <th style="width:20%;"><strong>Ação</strong></th>
                <th style="width:20%;"><strong>Seção</strong></th>
                <th style="width:30%;"><strong>Descrição</strong></th>
                <th style="width:5%;" class="text-center"><strong>-</strong></th>
              </tr>
            </thead>
            <tbody class="no-border-y">
              <?php foreach ( $data['list'] as $row ): ?>
                <tr name=log" id="<?php echo $row['id_log']; ?>">
                  <td><?php echo $row['inc_date']; ?></td>
                  <td><?php echo $row['admin']; ?></td>
                  <td><?php echo $row['action']; ?></td>
                  <td><?php echo $row['tbl']; ?></td>
                  <td><?php echo $row['description']; ?></td>
                  <td class="text-center">
                    <a class="label label-default btn_edit" href="#">
                      <i class="fa fa-clipboard"></i>
                    </a>
                  </td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>

          {$PAGINATION}

        </div>
      </div>
    </div>
  </div>
</div>

