<input type="hidden" id="link_prefix" value="/admin/log" />

<div class="row">
  <div class="col-md-12">

    <div class="block-flat">
      <div class="header">
        <h3>Visualização de Log</h3>
      </div>
      <div class="content">

        <div class="form-group form-group-submit">
          <span class="loadingsubmit"></span>
          <div class="input-group">
            <a href="#" title="Voltar para a lista" class="btn btn-default btn-rad btn_list btn_space">Voltar para lista</a>
          </div>
        </div>

        <form id="main_form" class="form-horizontal group-border-dashed" method="" style="border-radius: 0px;">

          <div class="form-group">
            <label class="col-sm-2 control-label">Data</label>
            <div class="col-sm-10">
              <label class="checkbox-inline"><?php echo $data['table']['inc_date']; ?></label>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Administrador</label>
            <div class="col-sm-10">
              <label class="checkbox-inline"><?php echo $data['table']['admin']; ?></label>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Ação</label>
            <div class="col-sm-10">
              <label class="checkbox-inline"><?php echo $data['table']['action']; ?></label>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Seção</label>
            <div class="col-sm-10">
              <label class="checkbox-inline"><?php echo $data['table']['tbl']; ?></label>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Descrição</label>
            <div class="col-sm-10">
              <label class="checkbox-inline"><?php echo $data['table']['description']; ?></label>
            </div>
          </div>

          <?php if ( $data['table']['cont'] ): ?>

            <div class="form-group">
              <label class="col-sm-3 control-label"><h2>Conteúdo</h2></label>
            </div>

            <?php foreach ( $data['table']['cont'] as $key => $row ): ?>
              <?php if ( is_object($row) ): ?>
                <div class="form-group">
                  <label class="col-sm-2 control-label"><?php echo $key; ?></label>
                  <div class="col-sm-10">
                    <div class="log_default log_before"><?php echo $row->before; ?></div>
                    <div><?php echo $row->after; ?></div>
                  </div>
                </div>
              <?php elseif ( is_string($row) ): ?>
                <div class="form-group">
                  <label class="col-sm-2 control-label"><?php echo $key; ?></label>
                  <div class="col-sm-10">
                    <div class="log_default"><?php echo $row; ?></div>
                  </div>
                </div>
              <?php endif; ?>
            <?php endforeach; ?>
          <?php else: ?>
            <div class="form-group">
              <label class="col-sm-3 control-label"><h3>Nada foi alterado.</h3></label>
            </div>
          <?php endif; ?>

        </form>
      </div>
    </div>

  </div>
</div>