<input type="hidden" id="link_prefix" value="/admin/log/" />

<div class="row">
  <div class="col-md-12">

    {$ALERT}

    <div class="block-flat">
      <div class="header">
        <h3>Lista de Log</h3>
      </div>

      <div class="content">
        <form method="get" class="form_busca">
          <div class="col-sm-4 col-md-4 col-lg-2">
            <input class="form-control" name="usuario" type="text" placeholder="Busca por nome de usuário" value="<?php echo $data['busca']['usuario']; ?>">
          </div>
          <div class="col-sm-4 col-md-4 col-lg-2">
            <input class="form-control" name="descricao" type="text" placeholder="Busca por descrição" value="<?php echo $data['busca']['descricao']; ?>">
          </div>
          <div class="col-sm-4 col-md-4 col-lg-2">
            <?php echo $data['dropdown']['acao']; ?>
          </div>
          <div class="col-sm-4 col-md-4 col-lg-2">
            <?php echo $data['dropdown']['name']; ?>
          </div>
          <input type="button" value="Limpar" class="limpar_busca btn btn-default btn-rad" />
          <input type="submit" value="Buscar" class="btn btn-info btn-rad" />
        </form>
      </div>

      <div class="content">
        <div class="table-responsive">
          <table class="table no-border hover">
            <thead class="no-border">
              <tr>
                <th style="width:10%;"><strong>Data</strong></th>
                <th style="width:15%;"><strong>Usuário</strong></th>
                <th style="width:20%;"><strong>Ação</strong></th>
                <th style="width:20%;"><strong>Seção</strong></th>
                <th style="width:30%;"><strong>Descrição</strong></th>
                <th style="width:5%;" class="text-center"><strong>-</strong></th>
              </tr>
            </thead>
            <tbody class="no-border-y">
              <?php foreach ( $data['list'] as $row ): ?>
                <tr>
                  <td><?php echo $data['DateFormat']::filter_date($row['inc_data'], 'd/m H:i'); ?></td>
                  <td><?php echo $row['administrador']; ?></td>
                  <td><?php echo $data['Arrays']::logAcao($row['acao']); ?></td>
                  <td><?php echo $row['name']; ?></td>
                  <td><?php echo $row['descricao']; ?></td>
                  <td class="text-center">
                    <a class="label label-default btn_edicao" href="<?php echo $row['id_log']; ?>">
                      <i class="fa fa-clipboard"></i>
                    </a>
                  </td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>

          {$PAGINACAO}

        </div>
      </div>
    </div>
  </div>
</div>

