<div id="cl-wrapper" class="login-container">

  <div class="middle-login">
    <div class="block-flat">
      <div class="header">
        <h3 class="text-center"><img class="logo-img" src="/admin/images/logo.png" alt="logo"/>DIN DIGITAL</h3>
      </div>
      <div>
        <form style="margin-bottom: 0px !important;" class="ajaxform form-horizontal" method="post" action="" autocomplete="on" onsubmit="return false;">

          <div class="content">

            <?php if ( isset($data['saved_msg']) ): ?>
              <div class="alert alert-success alert-success-fade">
                <i class="fa fa-check sign"></i><strong><?php echo $data['saved_msg']; ?></strong>
              </div>
            <?php endif; ?>
            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <i class="fa fa-times-circle sign"></i>
              <strong>Erro!</strong>
              <div></div>
            </div>
            <div class="alert alert-success">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <i class="fa fa-check sign"></i><strong>Sucesso!</strong>
              <div></div>
            </div>

            <h4 class="title">Acessar painel de controle</h4>
            <div class="form-group">
              <div class="col-sm-12">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-user"></i></span>
                  <input name="email" type="text" placeholder="E-mail" id="username" class="form-control">
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-12">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                  <input name="password" type="password" placeholder="Senha" id="password" class="form-control">
                </div>
              </div>
            </div>

          </div>

          <div class="foot">
            <span class="loadingsubmit"></span>
            <a class="btn_lostpass btn btn-default">Esqueci minha senha</a>
            <button class="btn btn-primary" data-dismiss="modal" type="submit">Acessar</button>
          </div>

        </form>
      </div>
    </div>
    <div class="text-center out-links"><a href="#">&copy; 2014 DIN DIGITAL</a></div>
  </div>

</div>