<div id="cl-wrapper" class="login-container">

  <div class="middle-login">
    <div class="block-flat">
      <div>
        <form style="margin-bottom: 0px !important;" class="ajaxform form-horizontal" method="post" action="" autocomplete="off" onsubmit="return false;">

          <div class="content">

            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <i class="fa fa-times-circle sign"></i>
              <strong>Erro!</strong>
              <div></div>
            </div>

            <h4 class="title">Recuperar Senha</h4>
            <div class="form-group">
              <div class="col-sm-12">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                  <input name="password" type="password" placeholder="Digite a nova senha" class="form-control">
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-12">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                  <input name="password2" type="password" placeholder="Confirme sua nova senha" class="form-control">
                </div>
              </div>
            </div>

          </div>

          <div class="foot">
            <span class="loadingsubmit"></span>
            <button class="btn btn-primary" data-dismiss="modal" type="submit">Alterar senha</button>
          </div>

        </form>
      </div>
    </div>
    <div class="text-center out-links"><a href="#">&copy; 2014 DIN DIGITAL</a></div>
  </div>

</div>