<input type="hidden" id="link_prefix" value="/admin/trash/" />

<div class="row">
  <div class="col-md-12">

    {$ALERT}

    <div class="block-flat">
      <div class="header">
        <h3>Lixeira</h3>
      </div>

      <div class="content">
        <form method="get" class="form_search">
          <div class="col-sm-4 col-md-4 col-lg-2">
            <input class="form-control" name="title" type="text" placeholder="Busca por título" value="<?php echo $data['search']['title']; ?>">
          </div>
          <div class="col-sm-4 col-md-4 col-lg-2">
            <?php echo $data['search']['section']; ?>
          </div>
          <input type="button" value="Limpar" class="clean_search btn btn-default btn-rad" />
          <input type="submit" value="Buscar" class="btn btn-info btn-rad" />
        </form>
      </div>

      <div class="content">
        <div class="col-lg-12 pull-left">
          <a href="#" title="Restaurar Selecionados" class="btn btn-primary btn-rad trash_re">Restaurar Selecionados</a>
          <a href="#" title="Excluir Selecionados Permamentemente" class="trash_ex btn btn-danger btn-rad">Excluir Selecionados Permamentemente</a>
        </div>
        <br style="clear: both;" />
      </div>

      <div class="content">
        <div class="table-responsive">
          <table class="table no-border hover">
            <thead class="no-border">
              <tr>
                <th style="width:2%;"><input type="checkbox" name="delete[]" id="delete_all" /></th>
                <th style="width:25%;"><strong>Data</strong></th>
                <th><strong>Título</strong></th>
                <th style="width:15%;"><strong>Seção</strong></th>
              </tr>
            </thead>
            <tbody class="no-border-y">
              <?php foreach ( $data['list'] as $row ): ?>
                <tr name="<?php echo $row['name']; ?>" id="<?php echo $row['id']; ?>">
                  <td><input class="delete" type="checkbox" name="delete[]" /></td>
                  <td><?php echo $row['del_date']; ?></td>
                  <td><?php echo $row['title']; ?></td>
                  <td><?php echo $row['section']; ?></td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>

          {$PAGINATION}

        </div>
      </div>
    </div>
  </div>
</div>

