<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Tweets Enviados</h3>
      </div>
      <div class="content">
        <div class="form-group form-group-submit">
          <span class="loadingsubmit"></span>
          <div class="input-group">
            <a href="<?php echo $data['redirect']; ?>" title="Voltar para a lista" class="btn btn-default btn-rad btn_space">Voltar</a>
          </div>
        </div>
        <?php foreach ( $data['tweets'] as $tweet ): ?>
          <div class="form-group">
            <label class="ccontrol-label">Enviado em <?php echo $tweet['date'] ?></label>
            <div>
                <label class="checkbox-inline"><?php echo $tweet['msg']; ?></label>
            </div>
          </div>
        <?php endforeach; ?>
      </div>
    </div>

  </div>
</div>