<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Envio de Tweet</h3>
      </div>
      <div class="content">

        <form id="main_form" class="ajaxform form-horizontal group-border-dashed" method="post" style="border-radius: 0px;" onsubmit="return false;">
          <input type="hidden" name="redirect" value="<?php echo $data['redirect']; ?>" />

          <div class="form-group form-group-submit">
            <span class="loadingsubmit"></span>
            <div class="input-group">
              <div class="input-group-btn">
                <button type="submit" class="btn btn-default" tabindex="-1" title="Enviar">Enviar</button>
              </div>
              <a href="<?php echo $data['redirect']; ?>" title="Voltar para a lista" class="btn btn-default btn-rad btn_space">Voltar</a>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Mensagem</label>
            <div class="col-sm-10">
              <textarea name="msg" class="form-control limit_text" maxlength="140" rows="4" placeholder="Escreva aqui o tweet"><?php echo $data['tweet']; ?></textarea>
              <div class="limit_info"></div>
            </div>
          </div>

          <div class="form-group form-group-submit">
            <span class="loadingsubmit"></span>
            <button type="submit" class="btn btn-default" tabindex="-1">Enviar</button>
          </div>

        </form>
      </div>
    </div>

  </div>
</div>