<html>
  <body>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td align="center" valign="middle"><table width="600" border="0" cellspacing="0" cellpadding="0" style="border:1px solid #dddddd;">
            <tr>
              <td align="center" valign="top"><img src="<?php echo URL; ?>/admin/images/header_email.jpg" alt="" width="600" height="50" /></td>
            </tr>
            <tr>
              <td align="center" valign="top"><br />
                <table width="550" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td>
                      <p style="font-family:Verdana;color:#656764;font-size:12px;">Olá</strong>,
                        <br />
                        Obrigado por utilizar nosso sistema administrativo!
                      </p>
                      <p style="font-family:Verdana;color:#656764;font-size:12px;">
                        Para gerar uma nova senha clique no link abaixo:
                      </p>
                      <p style="font-family:Verdana;color:#656764;font-size:12px;">
                        <a href="<?php echo $data['link'] ?>" title="Gerar nova senha">Gerar nova senha</a>
                      </p>
                      <p style="font-family:Verdana;color:#656764;font-size:10px;">Obs: O link tem validade de 12 horas e quando acesso pela primeira vez não poderá ser mais utilizado.</p>
                      <br />
                    </td>
                  </tr>
                </table>
                <br />
              </td>
            </tr>
          </table></td>
      </tr>
    </table>
  </body>
</html>