 <div class="jumbotron">
   <h1><?php echo $data['settings']['home_title'] ?></h1>
   <p class="lead"><?php echo $data['settings']['home_description'] ?></p>
   <h2><?php echo $data['settings']['title'] ?></h2>
   <p class="lead"><?php echo $data['settings']['description'] ?></p>
 </div>

 <hr>

 <?php if(isset($data['news']) && count($data['news'])): ?>
    <div class="row-fluid">
        <?php foreach ($data['news'] as $row): ?>
        <div class="span4">
            <h3><?php echo $row['title'] ?></h3>
            <h6><?php echo $row['date'] ?></h6>
            <p><?php echo $row['category'] ?></p>
            <p><a class="btn" href="<?php echo $row['uri'] ?>">Saiba mais &raquo;</a></p>
        </div>
        <?php endforeach; ?>
    </div>
 <?php endif; ?>

 <hr>