<div>
  <h1><?php echo $data['settings']['home_title'] ?></h1>
  <h2><?php echo $data['settings']['home_description'] ?></h2>
  <h3><?php echo $data['settings']['home_keywords'] ?></h3>
  <h4><a href="https://github.com/dindigital/skeleton" target="_blank">Github</a></h4>
</div>

<hr />

<?php if ( isset($data['news']) && count($data['news']) ): ?>
  <ul>
    <?php foreach ( $data['news'] as $row ): ?>
      <li>
        <h3><?php echo $row['title'] ?></h3>
        <h6><?php echo $row['date'] ?></h6>
        <p><?php echo $row['category'] ?></p>
        <p><a href="<?php echo $row['uri'] ?>" role="button">Saiba mais</a></p>
      </li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>

<hr>