 <div class="jumbotron">
   <h1>Lista de Notícias</h1>
 </div>

<div class="row">
    <ul>
        <?php foreach ($this->_data['news'] as $row): ?>
            <li>
                <a href="<?php echo $row['uri']; ?>" title="<?php echo $row['title']; ?>">
                    <?php echo $row['date']; ?> - <?php echo $row['title']; ?>
                </a>
                <p>
                    <?php echo $row['head']; ?>
                </p>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

 <hr>