<h1>Lista de Notícias</h1>

<table>
  <thead>
    <tr>
      <th width="100">&nbsp;</th>
      <th width="100">Data</th>
      <th width="300">Título</th>
      <th width="100">&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ( $this->_data['news'] as $row ): ?>
      <tr>
        <td><?php echo $row['cover']; ?></td>
        <td><?php echo $row['date']; ?></td>
        <td><?php echo $row['title']; ?></td>
        <td><a href="<?php echo $row['uri']; ?>" title="<?php echo $row['title']; ?>">Saiba Mais</a></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<hr>

<?php if ( $data['paginator']['numbers'] ): ?>
  <ul>
    <?php echo $data['paginator']['numbers']; ?>
  </ul>
<?php endif; ?>