<h1>Lista de Notícias</h1>

<table>
  <thead>
    <tr>
      <th width="100">&nbsp;</th>
      <th width="100">Data</th>
      <th width="300">Título</th>
      <th width="100">&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ( $data['news'] as $news ): ?>
      <tr>
        <td><?php echo $news->getCover(); ?></td>
        <td><?php echo $news->getDate(); ?></td>
        <td><?php echo $news->getTitle(); ?></td>
        <td><a href="<?php echo $news->getUri(); ?>" title="<?php echo $news->getTitle(); ?>">Saiba Mais</a></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<hr>

<?php if ( $data['paginator']['numbers'] ): ?>
  <ul>
    <?php echo $data['paginator']['numbers']; ?>
  </ul>
<?php endif; ?>