<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="images/favicon.png">

    <title>DIN DIGITAL</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,400italic,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:300,200,100' rel='stylesheet' type='text/css'>

    <link href="/admin/js/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="/admin/fonts/font-awesome-4/css/font-awesome.min.css">
    <link href="/admin/css/style.css" rel="stylesheet" />

  </head>

  <body class="texture">

    <div id="cl-wrapper" class="error-container">
      <div class="page-error">
        <h1 class="number text-center">500</h1>
        <h2 class="description text-center">Ops, ocorreu algum problema!</h2>
        <h3 class="text-center">Por favor entre em contato com o suporte usando o e-mail: <a href="mailto:suporte@dindigital.com">suporte@dindigital.com</a>.</h3>
      </div>
      <div class="text-center copy">&copy; 2014 <a href="#">DIN DIGITAL</a></div>

    </div>

    <script src="//code.jquery.com/jquery-1.9.1.js"></script>
    <script src="/admin/js/bootstrap/dist/js/bootstrap.min.js"></script>
  </body>
</html>
