<input type="hidden" id="link_prefix" value="/admin/<?php echo $this->_data['entity']['tbl']; ?>/" />

<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de <?php echo $this->_data['entity']['section']; ?></h3>
      </div>
      <div class="content">

        <form id="main_form" class="ajaxform form-horizontal group-border-dashed" method="post" style="border-radius: 0px;" onsubmit="return false;">

          <input type="hidden" name="redirect" value="save" />

          {$SUBMIT}

          <div class="form-group">
            <label class="col-sm-2 control-label" for="active">Ativo</label>
            <div class="col-sm-10">
              <label class="checkbox-inline"><input type="checkbox" name="active" id="active" <?php if ( $data['table']['active'] == '1' ): ?>checked="checked"<?php endif; ?> /></label>
            </div>
          </div>

          <?php if ( $data['table']['has_sc'] == '1' ): ?>
            <div class="form-group">
              <label class="col-sm-2 control-label">Publicação SoundCloud</label>
              <div class="col-sm-10">
                <a href="<?php echo $data['table']['soundcloud_link']; ?>" target="_blank"><?php echo $data['table']['soundcloud_link']; ?></a>
                <br />
                <label class="checkbox-inline"><input type="checkbox" name="republish_sc" />Atualizar Publicação SoundCloud</label>
                <br />
                <?php echo $data['table']['soundcloud_html']; ?>
              </div>
            </div>
          <?php else: ?>
            <div class="form-group">
              <label class="col-sm-2 control-label" for="active">Publicar no SoundCloud</label>
              <div class="col-sm-10">
                <label class="checkbox-inline"><input type="checkbox" name="publish_sc" /></label>
              </div>
            </div>
          <?php endif; ?>

          <div class="form-group">
            <label class="col-sm-2 control-label">Título</label>
            <div class="col-sm-10">
              <input name="title" type="text" value="<?php echo $data['table']['title']; ?>" placeholder="Título" class="form-control limit_text" maxlength="130">
              <div class="limit_info"></div>
            </div>
          </div>

          {$URI}

          <div class="form-group">
            <label class="col-sm-2 control-label">Descrição</label>
            <div class="col-sm-10">
              <textarea name="description" class="form-control limit_text" rows="4" placeholder="Descrição" maxlength="156"><?php echo $data['table']['description']; ?></textarea>
              <div class="limit_info"></div>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Data</label>
            <div class="col-sm-10">
              <input name="date" type="text" value="<?php echo $data['table']['date']; ?>" placeholder="Data" class="form-control dateMask">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Arquivo</label>
              <div class="col-sm-10">
                <label><input type="checkbox" name="file_delete" /> Remover arquivo</label>
                <br />
                <?php echo $data['table']['file_uploader']; ?>
              </div>
          </div>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>