<div class="row">
  <div class="col-md-12">

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de Configuração</h3>
      </div>
      <div class="content">

        {$ALERTS}

        <form id="main_form" class="form-horizontal group-border-dashed validate_form" method="post" style="border-radius: 0px;">

          <div class="form-group">
            <label class="col-sm-3 control-label">Título Home</label>
            <div class="col-sm-6">
              <input name="title_home" type="text" value="<?php echo $data['table']['title_home']; ?>" placeholder="Título da home" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">Description Home</label>
            <div class="col-sm-6">
              <textarea name="description_home" class="form-control" rows="4" placeholder="Descrição da home"><?php echo $data['table']['description_home']; ?></textarea>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">Keywords Home</label>
            <div class="col-sm-6">
              <input name="keywords_home" class="tags" type="hidden" value="<?php echo $data['table']['keywords_home']; ?>" />
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">Título Internas</label>
            <div class="col-sm-6">
              <input name="title_interna" type="text" value="<?php echo $data['table']['title_interna']; ?>" placeholder="Título das páginas internas" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">Description Internas</label>
            <div class="col-sm-6">
              <textarea name="description_interna" class="form-control" rows="4" placeholder="Descrição das páginas internas"><?php echo $data['table']['description_interna']; ?></textarea>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">Keywords Interna</label>
            <div class="col-sm-6">
              <input name="keywords_interna" class="tags" type="hidden" value="<?php echo $data['table']['keywords_interna']; ?>" />
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">Título Home</label>
            <div class="col-sm-6">
              <input name="qtd_horas" type="text" value="<?php echo $data['table']['qtd_horas']; ?>" placeholder="Horas" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">E-mail avisos</label>
            <div class="col-sm-6">
              <input name="email_avisos" type="text" value="<?php echo $data['table']['email_avisos']; ?>" placeholder="E-mail avisos" class="form-control">
            </div>
          </div>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>