<div class="row">
  <div class="col-md-12">

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de Exemplos</h3>
      </div>
      <div class="content">

        {$ALERTS}

        <form id="main_form" class="ajaxform form-horizontal group-border-dashed" method="post" style="border-radius: 0px;">

          {$SUBMIT}

          <div class="form-group">
            <label class="col-sm-2 control-label">Título Home</label>
            <div class="col-sm-10">
              <input name="title_home" type="text" value="" placeholder="Título da home" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Description Home</label>
            <div class="col-sm-10">
              <textarea name="description_home" class="form-control" rows="4" placeholder="Descrição da home"></textarea>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Keywords Home</label>
            <div class="col-sm-10">
              <input name="keywords_home" class="tags" type="hidden" value="mario,jair,mariana" />
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Select2</label>
            <div class="col-sm-10">
              <select class="select2">
                <optgroup label="Alaskan/Hawaiian Time Zone">
                  <option value="AK">Alaska</option>
                  <option value="HI">Hawaii</option>
                </optgroup>
                <optgroup label="Pacific Time Zone">
                  <option value="CA">California</option>
                  <option value="NV">Nevada</option>
                  <option value="OR">Oregon</option>
                  <option value="WA">Washington</option>
                </optgroup>
                <optgroup label="Mountain Time Zone">
                  <option value="AZ">Arizona</option>
                  <option value="CO">Colorado</option>
                  <option value="ID">Idaho</option>
                  <option value="MT">Montana</option><option value="NE">Nebraska</option>
                  <option value="NM">New Mexico</option>
                  <option value="ND">North Dakota</option>
                  <option value="UT">Utah</option>
                  <option value="WY">Wyoming</option>
                </optgroup>
                <optgroup label="Central Time Zone">
                  <option value="AL">Alabama</option>
                  <option value="AR">Arkansas</option>
                  <option value="IL">Illinois</option>
                  <option value="IA">Iowa</option>
                  <option value="KS">Kansas</option>
                  <option value="KY">Kentucky</option>
                  <option value="LA">Louisiana</option>
                  <option value="MN">Minnesota</option>
                  <option value="MS">Mississippi</option>
                  <option value="MO">Missouri</option>
                  <option value="OK">Oklahoma</option>
                  <option value="SD">South Dakota</option>
                  <option value="TX">Texas</option>
                  <option value="TN">Tennessee</option>
                  <option value="WI">Wisconsin</option>
                </optgroup>
                <optgroup label="Eastern Time Zone">
                  <option value="CT">Connecticut</option>
                  <option value="DE">Delaware</option>
                  <option value="FL">Florida</option>
                  <option value="GA">Georgia</option>
                  <option value="IN">Indiana</option>
                  <option value="ME">Maine</option>
                  <option value="MD">Maryland</option>
                  <option value="MA">Massachusetts</option>
                  <option value="MI">Michigan</option>
                  <option value="NH">New Hampshire</option><option value="NJ">New Jersey</option>
                  <option value="NY">New York</option>
                  <option value="NC">North Carolina</option>
                  <option value="OH">Ohio</option>
                  <option value="PA">Pennsylvania</option><option value="RI">Rhode Island</option><option value="SC">South Carolina</option>
                  <option value="VT">Vermont</option><option value="VA">Virginia</option>
                  <option value="WV">West Virginia</option>
                </optgroup>
              </select>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Multitag from Select</label>
            <div class="col-sm-10">
              <select class="select2" multiple>
                <optgroup label="Alaskan/Hawaiian Time Zone">
                  <option value="AK">Alaska</option>
                  <option value="HI">Hawaii</option>
                </optgroup>
                <optgroup label="Pacific Time Zone">
                  <option value="CA">California</option>
                  <option value="NV">Nevada</option>
                  <option value="OR">Oregon</option>
                  <option value="WA">Washington</option>
                </optgroup>
                <optgroup label="Mountain Time Zone">
                  <option value="AZ">Arizona</option>
                  <option value="CO">Colorado</option>
                  <option value="ID">Idaho</option>
                  <option value="MT">Montana</option><option value="NE">Nebraska</option>
                  <option value="NM">New Mexico</option>
                  <option value="ND">North Dakota</option>
                  <option value="UT">Utah</option>
                  <option value="WY">Wyoming</option>
                </optgroup>
                <optgroup label="Central Time Zone">
                  <option value="AL">Alabama</option>
                  <option value="AR">Arkansas</option>
                  <option value="IL">Illinois</option>
                  <option value="IA">Iowa</option>
                  <option value="KS">Kansas</option>
                  <option value="KY">Kentucky</option>
                  <option value="LA">Louisiana</option>
                  <option value="MN">Minnesota</option>
                  <option value="MS">Mississippi</option>
                  <option value="MO">Missouri</option>
                  <option value="OK">Oklahoma</option>
                  <option value="SD">South Dakota</option>
                  <option value="TX">Texas</option>
                  <option value="TN">Tennessee</option>
                  <option value="WI">Wisconsin</option>
                </optgroup>
                <optgroup label="Eastern Time Zone">
                  <option value="CT">Connecticut</option>
                  <option value="DE">Delaware</option>
                  <option value="FL">Florida</option>
                  <option value="GA">Georgia</option>
                  <option value="IN">Indiana</option>
                  <option value="ME">Maine</option>
                  <option value="MD">Maryland</option>
                  <option value="MA">Massachusetts</option>
                  <option value="MI">Michigan</option>
                  <option value="NH">New Hampshire</option><option value="NJ">New Jersey</option>
                  <option value="NY">New York</option>
                  <option value="NC">North Carolina</option>
                  <option value="OH">Ohio</option>
                  <option value="PA">Pennsylvania</option><option value="RI">Rhode Island</option><option value="SC">South Carolina</option>
                  <option value="VT">Vermont</option><option value="VA">Virginia</option>
                  <option value="WV">West Virginia</option>
                </optgroup>
              </select>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Basic Select</label>
            <div class="col-sm-10">
              <select class="form-control">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Multiple Select</label>
            <div class="col-sm-10">
              <select multiple class="form-control">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Radio</label>
            <div class="col-sm-10">
              <div class="radio">
                <label> <input type="radio" checked="" name="rad1"> Option 1</label>
              </div>
              <div class="radio">
                <label> <input type="radio" name="rad1"> Option 2</label>
              </div>
              <div class="radio">
                <label> <input type="radio" name="rad1"> Option 3</label>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Inline Radio</label>
            <div class="col-sm-10">
              <label class="radio-inline"> <input type="radio" checked="" name="rad1"> Option 1</label>
              <label class="radio-inline"> <input type="radio" name="rad1"> Option 2</label>
              <label class="radio-inline"> <input type="radio" name="rad1"> Option 3</label>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Checkbox</label>
            <div class="col-sm-10">
              <div class="radio">
                <label> <input type="checkbox" checked="" name="check1"> Option 1</label>
              </div>
              <div class="radio">
                <label> <input type="checkbox" name="check2"> Option 2</label>
              </div>
              <div class="radio">
                <label> <input type="checkbox" name="check3"> Option 3</label>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Inline Checkbox</label>
            <div class="col-sm-10">
              <label class="checkbox-inline"> <input type="checkbox" checked="" name="rad1"> Option 1</label>
              <label class="checkbox-inline"> <input type="checkbox" name="rad1"> Option 2</label>
              <label class="checkbox-inline"> <input type="checkbox" name="rad1"> Option 3</label>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">CEP Mask</label>
            <div class="col-sm-10">
              <input name="title_home" type="text" value="" placeholder="CEP" class="form-control cepMask">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">CPF Mask</label>
            <div class="col-sm-10">
              <input name="title_home" type="text" value="" placeholder="CPF" class="form-control cpfMask">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">CNPJ Mask</label>
            <div class="col-sm-10">
              <input name="title_home" type="text" value="" placeholder="CNPJ" class="form-control cnpjMask">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Telefone Mask</label>
            <div class="col-sm-10">
              <input name="title_home" type="text" value="" placeholder="Telefone" class="form-control telefoneMask">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Data Mask</label>
            <div class="col-sm-10">
              <input name="title_home" type="text" value="" placeholder="Data" class="form-control dataMask">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Hora Mask</label>
            <div class="col-sm-10">
              <input name="title_home" type="text" value="" placeholder="Horário" class="form-control horaMask">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Hora Full Mask</label>
            <div class="col-sm-10">
              <input name="title_home" type="text" value="" placeholder="Horário" class="form-control horafullMask">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Date Picker</label>
            <div class="col-sm-10">
              <input name="title_home" type="text" value="" placeholder="Data" class="form-control datepicker">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Color Basic</label>
            <div class="col-sm-10">
              <input name="title_home" type="text" value="" class="color_basic">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Color Full</label>
            <div class="col-sm-10">
              <input name="title_home" type="text" value="" class="color_full">
            </div>
          </div>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>