<div class="row">
  <div class="col-md-12">
    <div class="block-flat">
      <div class="header">
        <h3>Lista de Exemplos</h3>
      </div>

      <div class="content">

        <!-- ENVELOPE -->
        <a class="label label-info" href="#">
          <i class="fa fa-envelope-o"></i>
        </a>
        <!-- DOWNLOAD -->
        <a class="label label-default" href="#">
          <i class="fa fa-download"></i>
        </a>
        <!-- PRINT -->
        <a class="label label-info" href="#">
          <i class="fa fa-print"></i>
        </a>
        <!-- SETA DIREITA -->
        <a class="label label-primary" href="#">
          <i class="fa fa-mail-forward"></i>
        </a>
        <!-- PASTA -->
        <a class="label label-default" href="#">
          <i class="fa fa-folder"></i>
        </a>

        <form id="main_form" class="ajaxform form-horizontal group-border-dashed" method="post" style="border-radius: 0px;" onsubmit="return false;">
          <div class="form-group">
            <label class="col-sm-2 control-label">Date Picker</label>
            <div class="col-sm-10">
              <input name="title_home" type="text" value="" placeholder="Data" class="form-control datepicker">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Color Basic</label>
            <div class="col-sm-10">
              <input name="title_home" type="text" value="" class="color_basic">
            </div>
          </div>
        </form>

      </div>

    </div>
  </div>
</div>

