<div class="row">
  <div class="col-md-12">
    <div class="block-flat">
      <div class="header">
        <h3>Lista de Galerias de Foto</h3>
      </div>

      <div class="content">
        <form method="get" class="form_busca">
          <input type="hidden" id="link_prefix" value="/admin/usuario/" />
          <div class="col-sm-4 col-md-4 col-lg-2">
            <input class="form-control" name="nome" type="text" placeholder="Busca por nome" value="<?php echo $data['busca']['nome']; ?>">
          </div>
          <div class="col-sm-4 col-md-4 col-lg-2">
            <input class="form-control" name="email" type="text" placeholder="Busca por email" value="<?php echo $data['busca']['email']; ?>">
          </div>
          <input type="submit" value="Buscar" class="btn btn-info btn-rad" />
          <input type="button" value="Limpar" class="limpar_busca btn btn-default btn-rad" />
        </form>
      </div>

      <div class="content">
        <div class="col-lg-12 pull-left">
          <a href="/admin/usuario/cadastro/" title="Novo Registro" class="btn btn-primary btn-rad">Novo Registro</a>
          <a href="#" title="Excluir Selecionados" class="lixeira_ex btn btn-danger btn-rad">Excluir Selecionados</a>
        </div>
        <br style="clear: both;" />
      </div>

      <div class="content">
        <div class="table-responsive">
          <table class="table no-border hover">
            <thead class="no-border">
              <tr>
                <th style="width:2%;"><input type="checkbox" name="excluir[]" id="excluir_all" /></th>
                <th style="width:5%;"><strong>Ativo</strong></th>
                <th style="width:15%;"><strong>Titulo</strong></th>
                <th style="width:15%;"><strong>Data de Inclusão</strong></th>
                <th style="width:15%;" class="text-center"><strong>Ações</strong></th>
              </tr>
            </thead>
            <tbody class="no-border-y">
              <?php foreach ( $data['list'] as $row ): ?>
                <tr>
                  <td><input class="excluir" type="checkbox" name="excluir[]" id="exc_foto_<?php echo $row['id_foto']; ?>" /></td>
                  <td><input class="setAtivo" type="checkbox" <?php if ( $row['ativo'] == '1' ): ?> checked="checked"<?php endif; ?> id="<?php echo $row['id_foto']; ?>" /></td>
                  <td><?php echo $row['titulo']; ?></td>
                  <td><?php echo $data['DateFormat']::filter_date($row['inc_data']); ?></td>
                  <td class="text-center">
                    <a class="label label-default" href="/admin/foto/cadastro/<?php echo $row['id_foto']; ?>/">
                      <i class="fa fa-pencil"></i>
                    </a>
                    <a class="label label-danger excluir_shortcut" href="#">
                      <i class="fa fa-times"></i>
                    </a>
                  </td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>

          <?php if ( !count($data['list']) ): ?>
            <div class="header">
              <h4>Sua precisa não encontrou resultados</h4>
            </div>
          <?php else: ?>
            <div class="row">
              <div class="col-sm-12">
                <div class="pull-left">
                  <div class="dataTables_info" id="datatable_info">
                    Exibindo <?php echo $data['paginator']['subtotal']; ?> de <?php echo $data['paginator']['total']; ?> resultados
                  </div>
                </div>
                <div class="pull-right">
                  <div class="dataTables_paginate paging_bs_normal">
                    <ul class="pagination">
                      <?php echo $data['paginator']['numbers']; ?>
                    </ul>
                  </div>
                </div>
                <div class="clearfix">
                </div>
              </div>
            </div>
          <?php endif; ?>

        </div>
      </div>
    </div>
  </div>
</div>

