<div class="row">
  <div class="col-md-12">

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de Fotos</h3>
      </div>
      <div class="content">

        {$ALERTS}

        <form id="main_form" class="form-horizontal group-border-dashed validate_form" method="post" style="border-radius: 0px;">

          {$SUBMIT}

          <div class="form-group">
            <label class="col-sm-2 control-label" for="ativo">Ativo</label>
            <div class="col-sm-10">
              <input type="checkbox" name="ativo" id="ativo" <?php if ( @$data['table']['ativo'] == '1' ): ?>checked="checked"<?php endif; ?> />
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Título</label>
            <div class="col-sm-10">
              <input name="titulo" type="text" value="<?php echo @$data['table']['titulo']; ?>" placeholder="Título" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Data</label>
            <div class="col-sm-10">
              <input name="data" type="text" value="<?php echo @$data['table']['data']; ?>" placeholder="Data" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Galeria</label>
            <div class="col-sm-10">
              <?php echo @$data['table']['galeria_uploader'] ?>
            </div>
          </div>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>