<input type="hidden" id="link_prefix" value="/admin/foto/" />

<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de Fotos</h3>
      </div>
      <div class="content">

        <form id="main_form" class="ajaxform form-horizontal group-border-dashed" method="post" style="border-radius: 0px;" onsubmit="return false;">

          <input type="hidden" name="redirect" value="cadastro" />

          {$SUBMIT}

          <div class="form-group">
            <label class="col-sm-2 control-label" for="ativo">Ativo</label>
            <div class="col-sm-10">
              <label class="checkbox-inline"><input type="checkbox" name="ativo" id="ativo" <?php if ( @$data['table']['ativo'] == '1' ): ?>checked="checked"<?php endif; ?> /></label>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Título</label>
            <div class="col-sm-10">
              <input name="titulo" type="text" value="<?php echo @$data['table']['titulo']; ?>" placeholder="Título" class="limit_text form-control" maxlength="60">
              <div class="limit_info"></div>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Data</label>
            <div class="col-sm-10">
              <input name="data" type="text" value="<?php echo @$data['table']['data']; ?>" placeholder="Data" class="form-control dataMask">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Galeria</label>
            <div class="col-sm-10">
              <?php echo @$data['table']['galeria_uploader'] ?>
              <?php echo @$data['table']['galeria'] ?>
            </div>
          </div>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>