<div class="row">
  <div class="col-md-12">

    <div class="block-flat">
      <div class="header">
        <h3>Modelo de Institucional</h3>
      </div>
      <div class="content">
        <h4>Paragraph Text</h4>
        <p>To me this vast ivory-ribbed chest, with the long, unrelieved spine, extending far away from it in a straight line, not a little resembled the hull of a great ship new-laid upon the stocks, when only some twenty of her naked bow-ribs are inserted, and the keel is otherwise, for the time, but a long, disconnected timber.</p>
        <p class="text-right" >Herman Melville - Moby-Dick</p>

        <h4>Lead Paragraph</h4>
        <p class="lead">'I've heard something like it,' said Alice.</p>
        <p class="text-right">Lewis Carroll - Alice in Wonderland</p>

        <h4>Italic</h4>
        <p><i>"Consul," said he, "I have no longer any doubt. I have spotted my man.</i></p>
        <p class="text-right">Jules Verne - Around the World in 80 Days</p>

        <h4>Small</h4>
        <small>This is a tiny small text!</small><br/>

      </div>

      <div class="content">
        <h1>Heading Text 1</h1>
        <h2>Heading Text 2</h2>
        <h3>Heading Text 3</h3>
        <h4>Heading Text 4</h4>
        <h5>Heading Text 5</h5>
        <h6>Heading Text 6</h6>
        <div class="spacer">&nbsp;</div>
        <h1 class="hthin">Thin Heading 1</h1>
        <h2 class="hthin">Thin Heading 2</h2>
        <h3 class="hthin">Thin Heading 3</h3>
        <p class="spacer">
          To use thin headings, set <code>".hthin"</code> class in heading tag.
        </p>
      </div>

    </div>

  </div>
</div>