
<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Importação de Mailing</h3>
      </div>
      <div class="content">

        <form id="main_form" class="ajaxform form-horizontal group-border-dashed" method="post" style="border-radius: 0px;" onsubmit="return false;">

          <input type="hidden" id="link_prefix" value="/admin/mailing" />

          <input type="hidden" name="redirect" value="save" />

          <div class="form-group form-group-submit">
            <span class="loadingsubmit"></span>
            <div class="input-group">
              <div class="input-group-btn">
                <button type="submit" class="btn btn-default" tabindex="-1" title="Importar">Importar</button>
              </div>
              <a href="#" title="Voltar para a lista" class="btn btn-default btn-rad btn_list btn_space">Voltar</a>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Grupo</label>
            <div class="col-sm-10">
              <input name="mailing_group" type="hidden" style="width: 100%;" id="mailing" class="select2-ajax"/>
              <span class="select2-btns">
                <button class="btn btn-info btn-rad select2-btn-all" type="button">Adicionar todos</button>
                <button class="btn btn-warning btn-rad select2-btn-clear" type="button">Remover todos</button>
              </span>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Arquivo</label>
            <div class="col-sm-10">
              <?php echo $data['table']['xls_uploader']; ?>
            </div>
          </div>

          <div class="form-group form-group-submit">
            <span class="loadingsubmit"></span>
            <div class="input-group">
              <div class="input-group-btn">
                <button type="submit" class="btn btn-default" tabindex="-1" title="Importar">Importar</button>
              </div>
              <a href="#" title="Voltar para a lista" class="btn btn-default btn-rad btn_list btn_space">Voltar</a>
            </div>
          </div>

        </form>
      </div>
    </div>

  </div>
</div>