<input type="hidden" id="link_prefix" value="/admin/<?php echo $this->_data['entity']['tbl']; ?>/" />

<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de <?php echo $this->_data['entity']['section']; ?></h3>
      </div>
      <div class="content">

        <form id="main_form" class="ajaxform form-horizontal group-border-dashed" method="post" style="border-radius: 0px;" onsubmit="return false;">

          <input type="hidden" name="redirect" value="save" />

          {$SUBMIT}

          <div class="form-group">
            <label class="col-sm-2 control-label">Nome</label>
            <div class="col-sm-10">
              <input name="name" type="text" value="<?php echo $data['table']['name']; ?>" placeholder="Nome" class="limit_text form-control" maxlength="100">
              <div class="limit_info"></div>
            </div>
          </div>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>