<input type="hidden" id="link_prefix" value="/admin/<?php echo $this->_data['entity']['tbl']; ?>" />

<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de <?php echo $this->_data['entity']['section']; ?></h3>
      </div>
      <div class="content">

        <form id="main_form" class="form-horizontal group-border-dashed ajaxform" method="post" style="border-radius: 0px;" onsubmit="return false;">

          <input type="hidden" name="redirect" value="save" />

          {$SUBMIT}

          {$ACTIVE}

          <div class="form-group">
            <label class="col-sm-2 control-label">Categoria</label>
            <div class="col-sm-10">
              <div class="ajaxcat" data-response=".ajax-news-sub" data-uri="/admin/news_sub_ajax/">
                <?php echo $data['table']['id_news_cat']; ?>
              </div>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Subcategoria</label>
            <div class="col-sm-10">
              <div class="ajax-news-sub">
                <?php echo $data['table']['id_news_sub']; ?>
              </div>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Título</label>
            <div class="col-sm-10">
              <input name="title" type="text" value="<?php echo $data['table']['title']; ?>" placeholder="Título" class="form-control limit_text" maxlength="130">
            </div>
          </div>

          {$URI}

          <div class="form-group">
            <label class="col-sm-2 control-label">Data</label>
            <div class="col-sm-10">
              <input name="date" type="text" value="<?php echo $data['table']['date']; ?>" placeholder="Data" class="form-control dateMask">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Chamada</label>
            <div class="col-sm-10">
              <textarea name="head" placeholder="Chamada" class="form-control limit_text" maxlength="380"><?php echo $data['table']['head']; ?></textarea>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Capa</label>
            <div class="col-sm-10">
              <label><input type="checkbox" name="cover_delete" /> Remover arquivo</label>
              <br />
              <?php echo $data['table']['cover_uploader']; ?>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Corpo</label>
            <div class="col-sm-10">
              <?php echo $data['table']['body']; ?>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Fotos Relacionadas</label>
            <div class="col-sm-10">
              <input name="photo" type="hidden" style="width: 100%;" value="<?php echo $data['table']['id_news']; ?>" id="news" class="select2-static"/>
              <span class="select2-btns">
                <button class="btn btn-info btn-rad select2-btn-all" type="button">Adicionar todos</button>
                <button class="btn btn-warning btn-rad select2-btn-clear" type="button">Remover todos</button>
              </span>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Vídeos Relacionadas</label>
            <div class="col-sm-10">
              <input name="video" type="hidden" style="width: 100%;" value="<?php echo $data['table']['id_news']; ?>" id="news" class="select2-static"/>
              <span class="select2-btns">
                <button class="btn btn-info btn-rad select2-btn-all" type="button">Adicionar todos</button>
                <button class="btn btn-warning btn-rad select2-btn-clear" type="button">Remover todos</button>
              </span>
            </div>
          </div>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>