<input type="hidden" id="link_prefix" value="/admin/<?php echo $this->_data['entity']['tbl']; ?>/" />

<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de <?php echo $this->_data['entity']['section']; ?></h3>
      </div>
      <div class="content">

        <form id="main_form" class="form-horizontal group-border-dashed ajaxform" method="post" style="border-radius: 0px;" onsubmit="return false;">

          <input type="hidden" name="redirect" value="save" />

          {$SUBMIT}

          <div class="form-group">
            <label class="col-sm-2 control-label" for="active">Ativo</label>
            <div class="col-sm-10">
              <input type="checkbox" name="active" id="active" <?php if ($data['table']['active'] == '1'): ?>checked="checked"<?php endif; ?> />
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Título</label>
            <div class="col-sm-10">
              <input name="title" type="text" value="<?php echo $data['table']['title']; ?>" placeholder="Título" class="form-control limit_text" maxlength="130">
            </div>
          </div>

          {$URI}

          <div class="form-group">
            <label class="col-sm-2 control-label" for="home">Home</label>
            <div class="col-sm-10">
              <input type="checkbox" name="is_home" id="is_home" <?php if ($data['table']['is_home'] == '1'): ?>checked="checked"<?php endif; ?> />
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Capa</label>
            <div class="col-sm-10">
              <?php echo $data['table']['cover_uploader']; ?>
            </div>
          </div>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>