<input type="hidden" id="link_prefix" value="/admin/<?php echo $this->_data['entity']['tbl']; ?>/" />

<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de <?php echo $this->_data['entity']['section']; ?></h3>
      </div>
      <div class="content">

        <form id="main_form" class="form-horizontal group-border-dashed ajaxform" method="post" style="border-radius: 0px;" onsubmit="return false;">

          <input type="hidden" name="redirect" value="save" />

          {$SUBMIT}

          <div class="form-group">
            <label class="col-sm-2 control-label" for="active">Ativo</label>
            <div class="col-sm-10">
              <input type="checkbox" name="active" id="active" <?php if ( $data['table']['active'] == '1' ): ?>checked="checked"<?php endif; ?> />
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Título</label>
            <div class="col-sm-10">
              <input name="title" type="text" value="<?php echo $data['table']['title']; ?>" placeholder="Título" class="form-control limit_text" maxlength="130">
            </div>
          </div>

          {$URI}

          <div class="form-group">
            <label class="col-sm-2 control-label">Capa</label>
            <div class="col-sm-10">
              <?php echo $data['table']['cover']; ?>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Conteúdo</label>
            <div class="col-sm-10">
              <?php echo $data['table']['content']; ?>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Description</label>
            <div class="col-sm-10">
              <textarea name="description" class="form-control limit_text" maxlength="156" rows="4" placeholder="Descrição da página"><?php echo $data['table']['description']; ?></textarea>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Keywords</label>
            <div class="col-sm-10">
              <input name="keywords" class="tags" maxlength="255" type="hidden" value="<?php echo $data['table']['keywords']; ?>" />
            </div>
          </div>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>