<input type="hidden" id="link_prefix" value="/admin/<?php echo $this->_data['entity']['tbl']; ?>/" />

<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de <?php echo $this->_data['entity']['section']; ?></h3>
      </div>
      <div class="content">

        <form id="main_form" class="form-horizontal group-border-dashed ajaxform" method="post" style="border-radius: 0px;" onsubmit="return false;">

          <input type="hidden" id="id" value="<?php echo $data['table']['id_page']; ?>" />
          <input type="hidden" name="redirect" value="save" />

          {$SUBMIT}

          <div class="form-group">
            <label class="col-sm-2 control-label" for="active">Ativo</label>
            <div class="col-sm-10">
              <input type="checkbox" name="active" id="active" <?php if ( $data['table']['active'] == '1' ): ?>checked="checked"<?php endif; ?> />
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Menu</label>
            <div class="col-sm-10">
              <?php echo $data['table']['id_page_cat']; ?>
            </div>
          </div>

          <?php if ( $data['table']['id_parent'] ): ?>
            <?php foreach ( $data['table']['id_parent'] as $x => $dropdown ): ?>
              <div class="form-group drop_infinity_line<?php echo ($x > 0) ? ' other' : ''; ?>">
                <label class="col-sm-2 control-label">Página</label>
                <div class="col-sm-10 drop_infinity_container">
                  <?php echo $dropdown ?>
                </div>
              </div>
            <?php endforeach; ?>
          <?php else: ?>
            <div class="form-group drop_infinity_line" style="display: none">
              <label class="col-sm-2 control-label">Página</label>
              <div class="col-sm-10 drop_infinity_container">
              </div>
            </div>
          <?php endif; ?>

          <div class="form-group">
            <label class="col-sm-2 control-label">Título</label>
            <div class="col-sm-10">
              <input name="title" type="text" value="<?php echo $data['table']['title']; ?>" placeholder="Título" class="form-control limit_text" maxlength="130">
            </div>
          </div>

          {$URI}

          <div class="form-group">
            <label class="col-sm-2 control-label">Capa</label>
            <div class="col-sm-10">
              <label><input type="checkbox" name="cover_delete" /> Remover arquivo</label>
              <br />
              <?php echo $data['table']['cover_uploader']; ?>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Conteúdo</label>
            <div class="col-sm-10">
              <?php echo $data['table']['content']; ?>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Description</label>
            <div class="col-sm-10">
              <textarea name="description" class="form-control limit_text" maxlength="156" rows="4" placeholder="Descrição da página"><?php echo $data['table']['description']; ?></textarea>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Keywords</label>
            <div class="col-sm-10">
              <input name="keywords" maxlength="255" class="tags" type="hidden" value="<?php echo $data['table']['keywords']; ?>" />
            </div>
          </div>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>