<input type="hidden" id="link_prefix" value="/admin/<?php echo $this->_data['entity']['tbl']; ?>/" />

<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de <?php echo $this->_data['entity']['secao']; ?></h3>
      </div>
      <div class="content">

        <form id="main_form" class="form-horizontal group-border-dashed ajaxform" method="post" style="border-radius: 0px;" onsubmit="return false;">

          <input type="hidden" name="redirect" value="cadastro" />

          {$SUBMIT}

          <div class="form-group">
            <label class="col-sm-2 control-label" for="ativo">Ativo</label>
            <div class="col-sm-10">
              <input type="checkbox" name="ativo" id="ativo" <?php if ( @$data['table']['ativo'] == '1' ): ?>checked="checked"<?php endif; ?> />
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Menu</label>
            <div class="col-sm-10">
              <?php echo @$data['table']['id_pagina_cat']; ?>
            </div>
          </div>

          <?php if ( @$data['table']['infinito'] ): ?>
            <?php foreach ( $data['table']['infinito'] as $x => $dropdown ): ?>
              <div class="form-group drop_infinity_line<?php echo ($x > 0) ? ' other' : ''; ?>">
                <label class="col-sm-2 control-label">Página</label>
                <div class="col-sm-10 drop_infinity_container">
                  <?php echo $dropdown ?>
                </div>
              </div>
            <?php endforeach; ?>
          <?php else: ?>
            <div class="form-group drop_infinity_line" style="display: none">
              <label class="col-sm-2 control-label">Página</label>
              <div class="col-sm-10 drop_infinity_container">
              </div>
            </div>
          <?php endif; ?>

          <div class="form-group">
            <label class="col-sm-2 control-label">Título</label>
            <div class="col-sm-10">
              <input name="titulo" type="text" value="<?php echo @$data['table']['titulo']; ?>" placeholder="Título" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Capa</label>
            <div class="col-sm-10">
              <?php echo @$data['table']['capa']; ?>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Conteúdo</label>
            <div class="col-sm-10">
              <?php echo @$data['table']['conteudo']; ?>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Description</label>
            <div class="col-sm-10">
              <textarea name="description" class="form-control" rows="4" placeholder="Descrição da página"><?php echo @$data['table']['description']; ?></textarea>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Keywords</label>
            <div class="col-sm-10">
              <input name="keywords" class="tags" type="hidden" value="<?php echo @$data['table']['keywords']; ?>" />
            </div>
          </div>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>