<input type="hidden" id="link_prefix" value="/admin/<?php echo $this->_data['entity']['tbl']; ?>" />

<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de <?php echo $this->_data['entity']['section']; ?></h3>
      </div>
      <div class="content">

        <form id="main_form" class="form-horizontal group-border-dashed ajaxform" method="post" style="border-radius: 0px;" onsubmit="return false;">

          <input type="hidden" name="redirect" value="save" />

          {$SUBMIT}

          <div class="form-group">
            <label class="col-sm-2 control-label" for="active">Ativo</label>
            <div class="col-sm-10">
              <input type="checkbox" name="active" id="active" <?php if ( $data['table']['active'] == '1' ): ?>checked="checked"<?php endif; ?> />
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Pergunta</label>
            <div class="col-sm-10">
              <input name="question" type="text" value="<?php echo $data['table']['question']; ?>" placeholder="Pergunta" class="limit_text form-control" maxlength="130">
            </div>
          </div>

          {$URI}

          <fieldset class="duplication_container">
            <?php if ( $data['table']['id_poll'] ): ?>
              <?php foreach ( $data['table']['option'] as $option ): ?>
                <div class="form-group">
                  <label class="col-sm-2 control-label">Alternativa</label>
                  <div class="col-sm-10">
                    <input name="option[<?php echo $option['id_poll_option']; ?>]" type="text" value="<?php echo $option['option']; ?>" placeholder="Alternativa" class="limit_text form-control" maxlength="130">
                  </div>
                </div>
              <?php endforeach; ?>
            <?php else: ?>
              <div class="duplicate_part">
                <div class="form-group">
                  <label class="col-sm-2 control-label">Alternativa</label>
                  <div class="col-sm-10">
                    <input name="option[]" type="text" value="" placeholder="Alternativa" class="limit_text form-control" maxlength="130">
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                  <a class="add" style="cursor:pointer">ADICIONAR</a>
                  <a class="del" style="cursor:pointer; display:none">REMOVER</a>
                </div>
              </div>
            <?php endif; ?>
          </fieldset>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>