<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de <?php echo $this->_data['entity']['section']; ?></h3>
      </div>
      <div class="content">

        <form id="main_form" class="ajaxform form-horizontal group-border-dashed" method="post" style="border-radius: 0px;" onsubmit="return false;">


          <div class="form-group form-group-submit">
            <span class="loadingsubmit"></span>
            <button type="submit" class="btn btn-default" tabindex="-1">Salvar</button>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Título Home</label>
            <div class="col-sm-10">
              <input name="home_title" type="text" value="<?php echo $data['table']['home_title']; ?>" placeholder="Título da home" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Description Home</label>
            <div class="col-sm-10">
              <textarea name="home_description" class="form-control" rows="4" placeholder="Descrição da home"><?php echo $data['table']['home_description']; ?></textarea>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Keywords Home</label>
            <div class="col-sm-10">
              <input name="home_keywords" class="tags" type="hidden" value="<?php echo $data['table']['home_keywords']; ?>" />
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Título Internas</label>
            <div class="col-sm-10">
              <input name="title" type="text" value="<?php echo $data['table']['title']; ?>" placeholder="Título das páginas internas" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Description Internas</label>
            <div class="col-sm-10">
              <textarea name="description" class="form-control" rows="4" placeholder="Descrição das páginas internas"><?php echo $data['table']['description']; ?></textarea>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Keywords Interna</label>
            <div class="col-sm-10">
              <input name="keywords" class="tags" type="hidden" value="<?php echo $data['table']['keywords']; ?>" />
            </div>
          </div>

          <div class="form-group form-group-submit">
            <span class="loadingsubmit"></span>
            <button type="submit" class="btn btn-default" tabindex="-1">Salvar</button>
          </div>

        </form>
      </div>
    </div>

  </div>
</div>