<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de <?php echo $this->_data['entity']['section']; ?></h3>
      </div>
      <div class="content">

        <form id="main_form" class="ajaxform form-horizontal group-border-dashed" method="post" style="border-radius: 0px;" onsubmit="return false;">


          <div class="form-group form-group-submit">
            <span class="loadingsubmit"></span>
            <button type="submit" class="btn btn-default" tabindex="-1">Salvar</button>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">FB APP ID</label>
            <div class="col-sm-10">
              <input name="fb_app_id" type="text" value="<?php echo $data['table']['fb_app_id']; ?>" placeholder="" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">FB APP SECRET</label>
            <div class="col-sm-10">
              <input name="fb_app_secret" type="text" value="<?php echo $data['table']['fb_app_secret']; ?>" placeholder="" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">FB PAGE</label>
            <div class="col-sm-10">
              <input name="fb_page" type="text" value="<?php echo $data['table']['fb_page']; ?>" placeholder="" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">FB ACCESS TOKEN (don't touch)</label>
            <div class="col-sm-10">
              <input name="fb_access_token" type="text" value="<?php echo $data['table']['fb_access_token']; ?>" placeholder="" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">TW CONSUMER KEY</label>
            <div class="col-sm-10">
              <input name="tw_consumer_key" type="text" value="<?php echo $data['table']['tw_consumer_key']; ?>" placeholder="" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">TW CONSUMER SECRET</label>
            <div class="col-sm-10">
              <input name="tw_consumer_secret" type="text" value="<?php echo $data['table']['tw_consumer_secret']; ?>" placeholder="" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">TW ACCESS TOKEN</label>
            <div class="col-sm-10">
              <input name="tw_access_token" type="text" value="<?php echo $data['table']['tw_access_token']; ?>" placeholder="" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">TW ACCESS SECRET</label>
            <div class="col-sm-10">
              <input name="tw_access_secret" type="text" value="<?php echo $data['table']['tw_access_secret']; ?>" placeholder="" class="form-control">
            </div>
          </div>

          <div class="form-group form-group-submit">
            <span class="loadingsubmit"></span>
            <button type="submit" class="btn btn-default" tabindex="-1">Salvar</button>
          </div>

        </form>
      </div>
    </div>

  </div>
</div>