<input type="hidden" id="link_prefix" value="/admin/<?php echo $this->_data['entity']['tbl']; ?>/" />

<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de <?php echo $this->_data['entity']['section']; ?></h3>
      </div>
      <div class="content">

        <form id="main_form" class="form-horizontal group-border-dashed ajaxform" method="post" style="border-radius: 0px;" onsubmit="return false;">

          <input type="hidden" name="redirect" value="save" />

          {$SUBMIT}

          <div class="form-group">
            <label class="col-sm-2 control-label" for="active">Ativo</label>
            <div class="col-sm-10">
              <input type="checkbox" name="active" id="active" <?php if ( $data['table']['active'] == '1' ): ?>checked="checked"<?php endif; ?> />
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Título</label>
            <div class="col-sm-10">
              <input name="title" type="text" value="<?php echo $data['table']['title']; ?>" placeholder="Título" class="form-control">
            </div>
          </div>

          {$URI}

          <fieldset class="duplication_container">
            <?php if ( count($data['table']['question']) ): ?>
              <?php foreach ( $data['table']['question'] as $question ): ?>
                <div class="form-group">
                  <label class="col-sm-2 control-label">Questão</label>
                  <div class="col-sm-10">
                    <input name="question[<?php echo $question['id_survey_question']; ?>]" type="text" value="<?php echo $question['question']; ?>" placeholder="Questão" class="form-control">
                  </div>
                </div>
              <?php endforeach; ?>
            <?php else: ?>
              <div class="duplicate_part">
                <div class="form-group">
                  <label class="col-sm-2 control-label">Questão</label>
                  <div class="col-sm-10">
                    <input name="question[]" type="text" value="" placeholder="Título" class="form-control">
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                  <a class="add" style="cursor:pointer">ADICIONAR</a>
                  <a class="del" style="cursor:pointer; display:none">REMOVER</a>
                </div>
              </div>
            <?php endif; ?>
          </fieldset>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>