<input type="hidden" id="link_prefix" value="/admin/usuario/" />

<div class="row">
  <div class="col-md-12">
    <div class="block-flat">
      <div class="header">
        <h3>Lista de Usuários</h3>
      </div>

      <div class="content">
        <form method="get" class="form_busca">
          <div class="col-sm-4 col-md-4 col-lg-2">
            <input class="form-control" name="nome" type="text" placeholder="Busca por nome" value="<?php echo $data['busca']['nome']; ?>">
          </div>
          <div class="col-sm-4 col-md-4 col-lg-2">
            <input class="form-control" name="email" type="text" placeholder="Busca por email" value="<?php echo $data['busca']['email']; ?>">
          </div>
          <input type="button" value="Limpar" class="limpar_busca btn btn-default btn-rad" />
          <input type="submit" value="Buscar" class="btn btn-info btn-rad" />
        </form>
      </div>

      {$BTN_LISTA_CAD-EXC}

      <div class="content">
        <div class="table-responsive">
          <table class="table no-border hover">
            <thead class="no-border">
              <tr>
                <th style="width:2%;"><input type="checkbox" name="excluir[]" id="excluir_all" /></th>
                <th style="width:5%;"><strong>Ativo</strong></th>
                <th style="width:15%;"><strong>Nome</strong></th>
                <th style="width:15%;"><strong>E-mail</strong></th>
                <th style="width:15%;"><strong>Data de Inclusão</strong></th>
                <th style="width:15%;" class="text-center"><strong>Ações</strong></th>
              </tr>
            </thead>
            <tbody class="no-border-y">
              <?php foreach ( $data['list'] as $row ): ?>
                <tr>
                  <td><input class="excluir" type="checkbox" name="excluir[]" id="exc_usuario_<?php echo $row['id_usuario']; ?>" /></td>
                  <td><input class="setAtivo" type="checkbox" <?php if ( $row['ativo'] == '1' ): ?> checked="checked"<?php endif; ?> id="<?php echo $row['id_usuario']; ?>" /></td>
                  <td><?php echo $row['nome']; ?></td>
                  <td><?php echo $row['email']; ?></td>
                  <td><?php echo $data['DateFormat']::filter_date($row['inc_data']); ?></td>
                  <td class="text-center">
                    <a class="label label-default" href="/admin/usuario/cadastro/<?php echo $row['id_usuario']; ?>/">
                      <i class="fa fa-pencil"></i>
                    </a>
                    <a class="label label-danger excluir_shortcut" href="#">
                      <i class="fa fa-times"></i>
                    </a>
                  </td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>

          {$PAGINACAO}

        </div>
      </div>
    </div>
  </div>
</div>

