<input type="hidden" id="link_prefix" value="/admin/usuario/" />

<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de Usuário</h3>
      </div>
      <div class="content">

        <form id="main_form" class="ajaxform form-horizontal group-border-dashed" method="post" style="border-radius: 0px;" onsubmit="return false;">

          <input type="hidden" name="redirect" value="cadastro" />

          {$SUBMIT}

          <div class="form-group">
            <label class="col-sm-2 control-label" for="ativo">Ativo</label>
            <div class="col-sm-10">
              <label class="checkbox-inline"><input type="checkbox" name="ativo" id="ativo" <?php if ( @$data['table']['ativo'] == '1' ): ?>checked="checked"<?php endif; ?> /></label>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Nome</label>
            <div class="col-sm-10">
              <input name="nome" type="text" value="<?php echo @$data['table']['nome']; ?>" placeholder="Seu nome" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">E-mail</label>
            <div class="col-sm-10">
              <input name="email" type="text" value="<?php echo @$data['table']['email']; ?>" placeholder="Seu e-mail, ele será usado para o login" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Senha</label>
            <div class="col-sm-10">
              <input name="senha" class="form-control" type="password" value="" />
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Avatar</label>
            <div class="col-sm-10">
              <?php echo @$data['table']['avatar'] ?>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Avatar 2</label>
            <div class="col-sm-10">
              <?php echo @$data['table']['avatar2'] ?>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Avatar 3</label>
            <div class="col-sm-10">
              <?php echo @$data['table']['avatar3'] ?>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Permissões</label>
            <div class="col-sm-10">
              <?php echo @$data['table']['permissao'] ?>
            </div>
          </div>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>