<input type="hidden" id="link_prefix" value="/admin/<?php echo $this->_data['entity']['tbl']; ?>" />

<div class="row">
  <div class="col-md-12">

    {$ALERTS}

    <div class="block-flat">
      <div class="header">
        <h3>Cadastro de <?php echo $this->_data['entity']['section']; ?></h3>
      </div>
      <div class="content">

        <form id="main_form" class="ajaxform form-horizontal group-border-dashed" method="post" style="border-radius: 0px;" onsubmit="return false;">

          <input type="hidden" name="redirect" value="save" />

          {$SUBMIT}

          <div class="form-group">
            <label class="col-sm-2 control-label" for="active">Ativo</label>
            <div class="col-sm-10">
              <label class="checkbox-inline"><input type="checkbox" name="active" id="active" <?php if ( $data['table']['active'] == '1' ): ?>checked="checked"<?php endif; ?> /></label>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Título</label>
            <div class="col-sm-10">
              <input name="title" type="text" value="<?php echo $data['table']['title']; ?>" placeholder="Título" class="form-control limit_text" maxlength="130">
              <div class="limit_info"></div>
            </div>
          </div>

          {$URI}

          <div class="form-group">
            <label class="col-sm-2 control-label">Descrição</label>
            <div class="col-sm-10">
              <textarea name="description" class="form-control limit_text" rows="4" placeholder="Descrição" maxlength="156"><?php echo $data['table']['description']; ?></textarea>
              <div class="limit_info"></div>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Data</label>
            <div class="col-sm-10">
              <input name="date" type="text" value="<?php echo $data['table']['date']; ?>" placeholder="Data" class="form-control dateMask">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Link YouTube</label>
            <div class="col-sm-10">
              <input name="link_youtube" type="text" value="<?php echo $data['table']['link_youtube']; ?>" placeholder="Link do YouTube" class="youtube_link form-control">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Link Vimeo</label>
            <div class="col-sm-10">
              <input name="link_vimeo" type="text" value="<?php echo $data['table']['link_vimeo']; ?>" placeholder="Link do Vimeo" class="vimeo_link form-control" >
            </div>
          </div>

          <?php if ( !is_null($data['table']['id_youtube']) ): ?>
            <div class="form-group">
              <label class="col-sm-2 control-label">YouTube</label>
              <div class="col-sm-10">
                <label class="checkbox-inline"><input type="checkbox" name="republish_youtube" />Atualizar Publicação YouTube</label>
                <br />
                <iframe width="560" height="315" src="//www.youtube.com/embed/<?php echo $data['table']['id_youtube'] ?>?rel=0" frameborder="0" allowfullscreen></iframe>
              </div>
            </div>
          <?php else: ?>
            <div class="form-group">
              <label class="col-sm-2 control-label" for="active">Publicar no YouTube</label>
              <div class="col-sm-10">
                <label class="checkbox-inline"><input type="checkbox" name="publish_youtube" /></label>
              </div>
            </div>
          <?php endif; ?>

          <div class="form-group">
            <label class="col-sm-2 control-label">Arquivo</label>
            <div class="col-sm-10">
              <label><input type="checkbox" name="file_delete" /> Remover arquivo</label>
              <br />
              <?php echo $data['table']['file_uploader']; ?>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Relação Tags</label>
            <div class="col-sm-10">
              <input name="tag" type="hidden" style="width: 100%;" value="<?php echo $data['table']['id_video']; ?>" id="video" class="select2-ajax"/>
              <span class="select2-btns">
                <button class="btn btn-info btn-rad select2-btn-all" type="button">Adicionar todos</button>
                <button class="btn btn-warning btn-rad select2-btn-clear" type="button">Remover todos</button>
              </span>
            </div>
          </div>

          {$SUBMIT}

        </form>
      </div>
    </div>

  </div>
</div>